version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          paths:
            - /src/node_packages
          key: node_packages
      - run: npm run lint
  test:
    docker:
        - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - node_packages
      - run: npm i
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm audit

workflows:
  Pipelinohh:
    jobs:
      - build
      - test:
          requires:
            - build
      - audit:
          requires:
            - test
